name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'
    - name: Configure
#       run: ./configure --openssl-no-asm --without-intl --dest-cpu=x86_64
      run: ./configure --openssl-no-asm --without-intl --node-builtin-modules-path /Users/maxim/Projects/git/kmake
    - name: Compile
      run: make -j3
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kmake
        path: ${{github.workspace}}/out/Release/node
